### ISSUE TITLE
How can we use cameras with 30 or 60 fov

### ISSUE THREAD

**Issue by RYG81** [charlesveasey/UnityDomemaster#1]
Hi,
In my project I have camera fov set to 30 or max I can set it to 60. What suggestion are for that?
Going 90 makes my project useless. Is it possible to stay at 30 and still build for DOME? Or it requires to be 90 only?
Rahul

**Comment by charlesveasey** [comment]
Hi, 

With such a small field of view you can just use the camera shader option that is included. You then simply set the field of view on the camera as normal.

I just tested the included fisheye shader example and had a weird "not supported on this platform error". I was able to resolve it with a little bit of messing around. 

Try it and let me know if you get the same error on your computer, or this otherwise works for you.

best,
Charles

**Comment by RYG81** [comment]
I tried to use the shader but I have this error in shader
![error2](https://cloud.githubusercontent.com/assets/10570236/13106746/e8e02b28-d58f-11e5-826e-2999247d52a4.png)

**Comment by charlesveasey** [comment]
Thanks for pointing out the error. I've updated the project and package.
